name: Sync Fork Caller

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}

# Globale Berechtigungen f√ºr das Token des Callers
permissions:
  contents: write
  workflows: write

jobs:
  call-sync:
    uses: lemueIO/.github/.github/workflows/central-sync-logic.yml@main
    with:
      upstream_url: "https://github.com/derlemue/villa-kunterbunt.git"
    secrets: inherit
